In [30]:
import numpy as np
from sklearn import preprocessing ,cross_validation,svm
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.cluster import KMeans
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
import matplotlib.pyplot as plt
df=pd.read_csv('dataset5.csv')
print(df)

      Unnamed: 0   time  day  dustbin  percentage
0              0  11.00  0.0      0.0    2.000000
1              1  11.00  0.0      1.0   73.000000
2              2  11.00  0.0      2.0   28.000000
3              3  11.00  0.0      3.0   52.000000
4              4  11.00  0.0      4.0   63.000000
5              5  11.00  0.0      5.0   54.000000
6              6  11.00  0.0      6.0   22.000000
7              7  11.00  0.0      7.0   28.000000
8              8  11.00  0.0      8.0   13.000000
9              9  11.00  0.0      9.0   24.000000
10            10  11.00  0.0     10.0    5.000000
11            11  11.00  0.0     11.0   35.000000
12            12  11.00  0.0     12.0   26.000000
13            13  11.00  0.0     13.0   18.000000
14            14  11.00  0.0     14.0    1.000000
15            15  11.00  0.0     15.0   50.000000
16            16  11.00  0.0     16.0    7.000000
17            17  11.00  0.0     17.0   51.000000
18            18  11.00  0.0     18.0   31.000000


In [4]:
X=df.iloc[0:8000,[1,2,3]].values.astype(int)
y=df.iloc[0:8000,4].values.astype(int)
print(X)
print(y)
print(len(X))

[[11  0  0]
 [11  0  1]
 [11  0  2]
 ...
 [13  2 22]
 [13  2 23]
 [13  2 24]]
[ 2 73 28 ... 46 37 46]
8000


In [5]:
X_train ,X_test,y_train, y_test=cross_validation.train_test_split(X,y,test_size=0.2)

In [6]:
clf=svm.SVC()

In [7]:
clf.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
#print(cross_val_score(clf, X_test, y_test, cv=10, scoring='accuracy').mean())


In [9]:
xy=np.array([13 , 2 ,5]).reshape(1,-1)
#print(Xtest)
prdection=clf.predict(xy)
#x_test will be containg time and day for checking

#now we will see at present time which of dustbins are above 75%

In [10]:
print(prdection)

[17]


In [11]:
set1=set()
for i in range(len(prdection)):
    if prdection[i]>75:#threshold value 75%
        set1.add(i%25)

In [12]:
xy[0][0]=xy[0][0]+1
print(xy[0])
prdection=clf.predict(xy)
#x_test will be containg time + one hourrr   and day for checking

#now we will see at present time which of dustbins are above 90% predection for completion of bin
for i in range(len(prdection)):
    if prdection[i]>90:#threshold value 90%
        set1.add(i%25)

[14  2  5]


In [13]:
print(prdection)

[17]


# shortest path


In [14]:
from priodict import priorityDictionary

from collections import defaultdict

def Dijkstra(G, start, end=None):
   

    D = {}  # dictionary of final distances
    P = {}  # dictionary of predecessors
    Q = priorityDictionary()  # estimated distances of non-final vertices
    Q[start] = 0

    for v in Q:
        D[v] = Q[v]
        if v == end:
            break

        for w in G[v]:
            vwLength = D[v] + G[v][w]
            if w in D:
                if vwLength < D[w]:
                    raise ValueError("Dijkstra: found better path to already-final vertex")
            elif w not in Q or vwLength < Q[w]:
                Q[w] = vwLength
                P[w] = v

    return (D, P)


def shortestPath(G, start, end):
    """
    Find a single shortest path from the given start vertex to the given
    end vertex. The input has the same conventions as Dijkstra(). The
    output is a list of the vertices in order along the shortest path.
    """
    D, P = Dijkstra(G, start, end)
    Path = []
    while 1:
        Path.append(end)
        if end == start:
            break
        end = P[end]
    Path.reverse()
    return Path

def least(c,graph_to_visit,n,completed,cost):
    nc=999
    min_x=999
    kmin=0
    for i in range(n):
        if graph_to_visit[c][i]!=0 and completed[i]==0:
            if graph_to_visit[c][i]+graph_to_visit[i][c]<min_x:
                min_x=graph_to_visit[i][0]+graph_to_visit[c][i]
                kmin=graph_to_visit[c][i]
                nc=i
    if min_x!=999:
        cost+=kmin
        
    return (nc,cost)

def mincost(city,graph_to_visit,n,completed,cost=0,path=[]):
    completed[city]=1
#     print(city+1,"--> ",end=" " )
    path.append(city)

    ncity,cost=least(city,graph_to_visit,n,completed,cost)
    
    if ncity==999:
        ncity=0
        print(ncity+1)
        cost+=graph_to_visit[city][ncity]
        return (cost,path,completed)
    cost,path,completed=mincost(ncity,graph_to_visit,n,completed,cost,path)
    return (cost,path,completed)

if __name__ == "__main__":
    # n = int(input())
    # m = int(input())

    n = 7
    m = 8

    location_with_distance= [['1', '2', 3],
                             ['2', '3', 1],
                             ['4', '1', 10],
                             ['3', '4', 2],
                             ['4', '6', 7],
                             ['7', '5', 2],
                             ['3', '5', 1],
                             ['4', '5', 5]]
    
    set1.add('1')
    set1.add('4')
    set1.add('7')
    location_to_visit=list(set1)


    dustbins_location=[]
    main_graph=defaultdict(dict)
    gtime={}
    for i in range(0,m):
    #     input_path=input().split()

        input_path=location_with_distance[i]

    #     will store the time from one path to other path
        if(input_path[0]==input_path[1]):
            continue

        main_graph[input_path[0]][input_path[1]]=input_path[2]
        main_graph[input_path[1]][input_path[0]]=input_path[2]

    main_graph=dict(main_graph)
    print(main_graph)

    for i in main_graph:
        dustbins_location.append(i)


    number_of_location_to_visit=len(location_to_visit)
    graph_to_visit=[]  
    for i in range(number_of_location_to_visit):
        arr=[]
        for j in range(number_of_location_to_visit):
            arr.append(0)
        graph_to_visit.append(arr)
            
#     check all the combinations
    for i in range(number_of_location_to_visit-1):
        for j in range(i+1,number_of_location_to_visit):

            minimum_distance_list=shortestPath(main_graph,location_to_visit[i],location_to_visit[j])
#             print(minimum_distance_list)
            minimum_distance=0
            for x in range(len(minimum_distance_list)-1):
                minimum_distance+=main_graph[minimum_distance_list[x]][minimum_distance_list[x+1]]
#             print(total_dist)
            
            graph_to_visit[i][j]=graph_to_visit[j][i]=minimum_distance
        
    print("Graph to visit:" ,graph_to_visit)
        
    # graph_to_visit=[[0, 4, 1, 3],[4, 0, 2, 1],[1, 2, 0, 5],[3, 1, 5, 0]]
    completed=[]
    for i in range(number_of_location_to_visit):
        completed.append(0)
    cost,final_path,completed=mincost(0,graph_to_visit,3,completed)
    print("Total Cost(back to src):",cost)
    for i in range(len(final_path)): final_path[i]=location_to_visit[i]
    print("Sequence of path: ",final_path)
    
    final_full_path=[final_path[0]]
    for i in range(len(final_path)-1):
        minimum_distance_list=shortestPath(main_graph,final_path[i],final_path[i+1])
        print("aaaa: ",minimum_distance_list)
        final_full_path+=minimum_distance_list[1:-1]
        final_full_path+=[final_path[i+1]]
        
    print("Final Path to return: ")
    print(final_full_path)



{'1': {'2': 3, '4': 10}, '2': {'1': 3, '3': 1}, '3': {'2': 1, '4': 2, '5': 1}, '4': {'1': 10, '3': 2, '6': 7, '5': 5}, '6': {'4': 7}, '7': {'5': 2}, '5': {'7': 2, '3': 1, '4': 5}}
Graph to visit: [[0, 6, 5], [6, 0, 7], [5, 7, 0]]
1
Total Cost(back to src): 18
Sequence of path:  ['4', '1', '7']
aaaa:  ['4', '3', '2', '1']
aaaa:  ['1', '2', '3', '5', '7']
Final Path to return: 
['4', '3', '2', '1', '2', '3', '5', '7']


# sending data to server by the path obtained

In [15]:
df2=pd.read_csv('locations.csv')
print(df2)

    id    latitude  longitude
0    1    28.63133   77.37373
1    2     28.6189   77.37383
2    3    28.61761   77.37978
3    4    28.61085   77.35435
4    5    28.60087   77.37241
5    6    28.61794   77.36456
6    7     28.6315   77.35533
7    8    28.62408   77.36495
8    9    28.61873   77.34156
9   10    28.63237   77.33825
10  11    28.62231   77.33224
11  12    28.60573   77.33353
12  13    28.60012   77.35151
13  14    28.61033   77.37284
14  15     28.6182   77.35512
15  16    28.62743   77.38164
16  17    28.65624   77.37662
17  18   28 .64818   77.35945
18  19    28.64517   77.37889
19  20    28.63933   77.37040
20  21    28.62619   77.34838
21  22    28.61436   77.34825
22  23    28.62106   77.35941
23  24    28.62517   77.37443
24  25    28.60792   77.34190


In [25]:
X1=df2.iloc[0:,1].values.astype(str)
#print(X1.head)

In [28]:
we=np.array(['1','2','3','5','7','5','3','4'])
d = dict()
for i in range (len(we)):
    
    d[we[i]]=X1[i]

In [29]:
print(d)

{'1': '28.63133', '2': '28.6189', '3': '28.6315', '5': '28.61794', '7': '28.60087', '4': '28.62408'}
